name: test

on:
  push:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Build
      run: cargo build --release
    - name: 'Tar files'
      run: tar -cvzf render-deploy.tar.gz target/release/render-deploy
    - uses: actions/upload-artifact@v4
      with:
        if-no-files-found: error
        path: ./render-deploy.tar.gz
        name: render-deploy-linux.tar.gz
